Algoritmo "area_trapezio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : eu mesmo

Var

b, bm, h, area : real


Inicio

escreval("Este programa irá calcular a área de um trapezio.")
escreval
escreval("Digite a base maior:")
leia(bm)
escreval("Digite a base menor:")
leia(b)
escreval("Digite a altura:")
leia(h)

area <- (b + bm) / 2 * h
escreval
escreval("A área deste trapezio é:", area)


Fimalgoritmo