Algoritmo "soma"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 

Var

   nUm, nDois, soma : inteiro

Inicio

      escreval("Qual o valor do primeiro número?")
      leia(nUm)
      escreval

      escreval("Qual o valor do segundo número?")
      leia(nDois)
      escreval
      
      soma <- nUm + nDois
      
      escreval("A soma desses números é:", soma)
      

Fimalgoritmo